on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development
    paths-ignore:
      - 'docs/**'

name: golangci-lint

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix: # Pin go version to the one(s) below.
        go: [ '1.17' ]
    steps:
      - uses: actions/checkout@v3

      - name: Setup go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46.2
          skip-build-cache: true
          skip-pkg-cache: true
          args: --build-tags "containers_image_openpgp containers_image_ostree" --timeout 5m --skip-dirs internal/pkg/staticfiles

