on:
  push:
    branches:
      - main
  pull_request:

name: golangci-lint

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix: # Pin go version to the one(s) below.
        go ['1.17']
    steps:
      - uses: actions/checkout@v2

      - name Setup go ${{ matrix.go }}
        uses: actions/setup.go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.31
          skip-build-cache: true
          skip-pkg-cache: true
          args: --build-tags "containers_image_openpgp containers_image_ostree" --timeout 5m --skip-dirs internal/pkg/staticfiles

