---
name: test

on:
  push:
    branches:
      - main
      - development
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - main
      - development
    paths-ignore:
      - 'docs/**'

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.18', '1.19', '1.20' ]
    steps:
    - uses: actions/checkout@v3

    - name: Install gpgme
      run: sudo apt-get install libgpgme-dev

    - name: Setup go ${{ matrix.go }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
        cache: true

    - name: Build with go ${{ matrix.go }}
      run: make all

    - name: vet
      run: make vet

    - name: test
      run: make test
